CREATE TABLE ITEM (
    ITEM_ID             NUMBER(11, 0),
    NAME                VARCHAR(30),
    DESCRIPTION         VARCHAR(100),
    BRAND               VARCHAR(30),
    CODENAME            VARCHAR(10),
    IMAGE               BLOB,
    QR_CODE             VARCHAR(150),
    BAR_CODE            VARCHAR(150),
    CREATE_DATE         DATE DEFAULT SYSDATE,
    LAST_MODIFIED       DATE DEFAULT SYSDATE,
CONSTRAINT ITEM_PK PRIMARY KEY (ITEM_ID));

CREATE TABLE LOCATION (
    LOCATION_ID         NUMBER(11, 0),
    NAME                VARCHAR(30),
    DESCRIPTION         VARCHAR(100),
    IMAGE               BLOB,
    PARENT_LOCATION     NUMBER(11, 0),
    CREATE_DATE         DATE DEFAULT SYSDATE,
    LAST_MODIFIED       DATE DEFAULT SYSDATE,
CONSTRAINT LOC_PK PRIMARY KEY (LOCATION_ID),
CONSTRAINT LOC_FK1 FOREIGN KEY (PARENT_LOCATION) REFERENCES LOCATION(LOCATION_ID));

CREATE TABLE MEDIUM (
    MEDIUM_ID           NUMBER(11, 0),
    NAME                VARCHAR(30),
    DESCRIPTION         VARCHAR(100),
    IMAGE               BLOB,
    QR_CODE             VARCHAR(150),
    PARENT_LOCATION     NUMBER(11, 0),
    PARENT_MEDIUM_ID    NUMBER(11, 0),
    PATH                VARCHAR(150),
    CREATE_DATE         DATE DEFAULT SYSDATE,
    LAST_MODIFIED       DATE DEFAULT SYSDATE,
CONSTRAINT MED_PK PRIMARY KEY (MEDIUM_ID),
CONSTRAINT MED_FK1 FOREIGN KEY (PARENT_LOCATION) REFERENCES LOCATION(LOCATION_ID),
CONSTRAINT MED_FK2 FOREIGN KEY (PARENT_MEDIUM_ID) REFERENCES MEDIUM(MEDIUM_ID));

CREATE TABLE PASSWORD (
    PASSWORD_ID         NUMBER(11, 0),
    PASSWORD            VARCHAR(30),
    CREATE_DATE         DATE DEFAULT SYSDATE,
    LAST_MODIFIED       DATE DEFAULT SYSDATE,
CONSTRAINT PASS_PK PRIMARY KEY (PASSWORD_ID));

CREATE TABLE ITEM_MEDIUM (
    ITEM_MEDIUM_ID          NUMBER(11, 0),
    ITEM_ID                 NUMBER(11, 0),
    MEDIUM_ID               NUMBER(11, 0),
    ARCHIVE_STATUS          BLOB,
    TYPE                    VARCHAR(1),
    STATUS                  VARCHAR(15),
    QUANTITY                NUMBER(5, 0),
    START_CONSUMPTION_DATE  DATE DEFAULT SYSDATE,
    END_CONSUMPTION_DATE    DATE DEFAULT SYSDATE,
    CREATE_DATE             DATE DEFAULT SYSDATE,
    LAST_MODIFIED           DATE DEFAULT SYSDATE,
CONSTRAINT ITEM_MED_PK PRIMARY KEY (ITEM_MEDIUM_ID),
CONSTRAINT ITEM_MED_FK1 FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID),
CONSTRAINT ITEM_MED_FK2 FOREIGN KEY (MEDIUM_ID) REFERENCES MEDIUM(MEDIUM_ID));

CREATE TABLE RECORD (
    RECORD_ID           NUMBER(11, 0),
    ITEM_MEDIUM_ID      NUMBER(11, 0),
    QUANTITY_CHANGE     VARCHAR(6),
    CHANGE_DATE         DATE DEFAULT SYSDATE,
CONSTRAINT RECORD_PK PRIMARY KEY (RECORD_ID),
CONSTRAINT RECORD_FK1 FOREIGN KEY (ITEM_MEDIUM_ID) REFERENCES ITEM_MEDIUM(ITEM_MEDIUM_ID));

CREATE SEQUENCE ITEM_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1

CREATE SEQUENCE LOCATION_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1

CREATE SEQUENCE SUBLOCATION_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1

CREATE SEQUENCE MEDIUM_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1

CREATE SEQUENCE PASSWORD_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1

CREATE SEQUENCE ITEM_MEDIUM_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1

CREATE SEQUENCE RECORD_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1


SELECT *
FROM LOCATION
ORDER BY LAST_MODIFIED DESC
FETCH FIRST 5 ROWS ONLY;