CREATE TABLE ITEM (
    ITEM_ID             NUMBER(11, 0),
    NAME                VARCHAR(30),
    DESCRIPTION         VARCHAR(100),
    BRAND               VARCHAR(30),
    CODENAME            VARCHAR(10),
    IMAGE               BLOB,
    CREATE_DATE         DATE DEFAULT SYSDATE,
    LAST_MODIFIED       DATE DEFAULT SYSDATE,
CONSTRAINT ITEM_PK PRIMARY KEY (ITEM_ID));

CREATE TABLE LOCATION (
    LOCATION_ID         NUMBER(11, 0),
    NAME                VARCHAR(30),
    DESCRIPTION         VARCHAR(100),
    IMAGE               BLOB,
    PARENT_LOCATION     NUMBER(11, 0),
    CREATE_DATE         DATE DEFAULT SYSDATE,
    LAST_MODIFIED       DATE DEFAULT SYSDATE,
CONSTRAINT LOC_PK PRIMARY KEY (LOCATION_ID),
CONSTRAINT LOC_FK1 FOREIGN KEY (PARENT_LOCATION) REFERENCES LOCATION(LOCATION_ID));

CREATE TABLE MEDIUM (
    MEDIUM_ID           NUMBER(11, 0),
    NAME                VARCHAR(30),
    DESCRIPTION         VARCHAR(100),
    IMAGE               BLOB,
    PARENT_LOCATION     NUMBER(11, 0),
    PARENT_MEDIUM       NUMBER(11, 0),
    PATH                VARCHAR(150),
    CREATE_DATE         DATE DEFAULT SYSDATE,
    LAST_MODIFIED       DATE DEFAULT SYSDATE,
CONSTRAINT MED_PK PRIMARY KEY (MEDIUM_ID),
CONSTRAINT MED_FK1 FOREIGN KEY (PARENT_LOCATION) REFERENCES LOCATION(LOCATION_ID),
CONSTRAINT MED_FK2 FOREIGN KEY (PARENT_MEDIUM) REFERENCES MEDIUM(MEDIUM_ID));

CREATE TABLE PASSWORD (
    PASSWORD_ID         NUMBER(11, 0),
    PASSWORD            VARCHAR(30),
    CREATE_DATE         DATE DEFAULT SYSDATE,
    LAST_MODIFIED       DATE DEFAULT SYSDATE,
CONSTRAINT PASS_PK PRIMARY KEY (PASSWORD_ID));

CREATE TABLE ITEM_MEDIUM (
    ITEM_MEDIUM_ID          NUMBER(11, 0),
    ITEM_ID                 NUMBER(11, 0),
    MEDIUM_ID               NUMBER(11, 0),
    ARCHIVE_STATUS          VARCHAR(1),
    TYPE                    VARCHAR(1),
    STATUS                  VARCHAR(15),
    QUANTITY                NUMBER(5, 0),
    START_CONSUMPTION_DATE  DATE DEFAULT SYSDATE,
    END_CONSUMPTION_DATE    DATE DEFAULT SYSDATE,
    CREATE_DATE             DATE DEFAULT SYSDATE,
    LAST_MODIFIED           DATE DEFAULT SYSDATE,
CONSTRAINT ITEM_MED_PK PRIMARY KEY (ITEM_MEDIUM_ID),
CONSTRAINT ITEM_MED_FK1 FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ITEM_ID),
CONSTRAINT ITEM_MED_FK2 FOREIGN KEY (MEDIUM_ID) REFERENCES MEDIUM(MEDIUM_ID));

CREATE TABLE RECORD (
    RECORD_ID           NUMBER(11, 0),
    ITEM_MEDIUM_ID      NUMBER(11, 0),
    QUANTITY_CHANGE     VARCHAR(6),
    CHANGE_DATE         DATE DEFAULT SYSDATE,
CONSTRAINT RECORD_PK PRIMARY KEY (RECORD_ID),
CONSTRAINT RECORD_FK1 FOREIGN KEY (ITEM_MEDIUM_ID) REFERENCES ITEM_MEDIUM(ITEM_MEDIUM_ID));

CREATE SEQUENCE ITEM_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1;

CREATE SEQUENCE LOCATION_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1;

CREATE SEQUENCE MEDIUM_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1;

CREATE SEQUENCE PASSWORD_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1;

CREATE SEQUENCE ITEM_MEDIUM_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1;

CREATE SEQUENCE RECORD_SEQ
    INCREMENT BY 1
    START WITH 1
    MINVALUE 1;

INSERT INTO PASSWORD (PASSWORD_ID, PASSWORD, CREATE_DATE, LAST_MODIFIED)
            VALUES (PASSWORD_SEQ.nextval, 'imysm3000', sysdate, sysdate);

INSERT INTO ITEM (ITEM_ID, NAME, DESCRIPTION, BRAND, CREATE_DATE, LAST_MODIFIED)
            VALUES (ITEM_SEQ.nextval, 'Ballpen', 'For Writing', 'Panda', sysdate, sysdate);
INSERT INTO ITEM (ITEM_ID, NAME, DESCRIPTION, BRAND, CREATE_DATE, LAST_MODIFIED)
            VALUES (ITEM_SEQ.nextval, 'Alcohol', 'For Sanitation', 'Green Cross', sysdate, sysdate);
INSERT INTO ITEM (ITEM_ID, NAME, DESCRIPTION, BRAND, CREATE_DATE, LAST_MODIFIED)
            VALUES (ITEM_SEQ.nextval, 'Tissue', 'For Sipon', 'Shuta', sysdate, sysdate);

INSERT INTO LOCATION (LOCATION_ID, NAME, DESCRIPTION, PARENT_LOCATION, CREATE_DATE, LAST_MODIFIED)
            VALUES (LOCATION_SEQ.nextval, 'Home', 'Valenzuela', null, sysdate, sysdate);
INSERT INTO LOCATION (LOCATION_ID, NAME, DESCRIPTION, PARENT_LOCATION, CREATE_DATE, LAST_MODIFIED)
            VALUES (LOCATION_SEQ.nextval, 'Living Room', 'Valenzuela', 1, sysdate, sysdate);
INSERT INTO LOCATION (LOCATION_ID, NAME, DESCRIPTION, PARENT_LOCATION, CREATE_DATE, LAST_MODIFIED)
            VALUES (LOCATION_SEQ.nextval, 'Ron''s Room', 'Valenzuela', 1, sysdate, sysdate);
INSERT INTO LOCATION (LOCATION_ID, NAME, DESCRIPTION, PARENT_LOCATION, CREATE_DATE, LAST_MODIFIED)
            VALUES (LOCATION_SEQ.nextval, 'University', 'Manila', null, sysdate, sysdate);

INSERT INTO MEDIUM (MEDIUM_ID, NAME, DESCRIPTION, PARENT_LOCATION, PARENT_MEDIUM, PATH, CREATE_DATE, LAST_MODIFIED)
            VALUES (MEDIUM_SEQ.nextval, 'Black Cabinet', 'Lalagyan', 3, null, null, sysdate, sysdate);
INSERT INTO MEDIUM (MEDIUM_ID, NAME, DESCRIPTION, PARENT_LOCATION, PARENT_MEDIUM, PATH, CREATE_DATE, LAST_MODIFIED)
            VALUES (MEDIUM_SEQ.nextval, 'Top Left Container', 'Lalagyan', 3, 1, 1, sysdate, sysdate);
INSERT INTO MEDIUM (MEDIUM_ID, NAME, DESCRIPTION, PARENT_LOCATION, PARENT_MEDIUM, PATH, CREATE_DATE, LAST_MODIFIED)
            VALUES (MEDIUM_SEQ.nextval, 'Top Right Container', 'Lalagyan', 3, 1, 1, sysdate, sysdate);
INSERT INTO MEDIUM (MEDIUM_ID, NAME, DESCRIPTION, PARENT_LOCATION, PARENT_MEDIUM, PATH, CREATE_DATE, LAST_MODIFIED)
            VALUES (MEDIUM_SEQ.nextval, 'Black Box', 'Lalagyan', 3, 2, '1,2', sysdate, sysdate);
INSERT INTO MEDIUM (MEDIUM_ID, NAME, DESCRIPTION, PARENT_LOCATION, PARENT_MEDIUM, PATH, CREATE_DATE, LAST_MODIFIED)
            VALUES (MEDIUM_SEQ.nextval, 'Small Ring Box', 'Lalagyan', 3, 4, '1,2,4', sysdate, sysdate);

INSERT INTO ITEM_MEDIUM (ITEM_MEDIUM_ID, ITEM_ID, MEDIUM_ID, ARCHIVE_STATUS, TYPE, STATUS, QUANTITY, START_CONSUMPTION_DATE, END_CONSUMPTION_DATE, CREATE_DATE, LAST_MODIFIED)
            VALUES (ITEM_MEDIUM_SEQ.nextval, 1, 4, 'V', 'R', null, 10, null, null, sysdate, sysdate);
INSERT INTO ITEM_MEDIUM (ITEM_MEDIUM_ID, ITEM_ID, MEDIUM_ID, ARCHIVE_STATUS, TYPE, STATUS, QUANTITY, START_CONSUMPTION_DATE, END_CONSUMPTION_DATE, CREATE_DATE, LAST_MODIFIED)
            VALUES (ITEM_MEDIUM_SEQ.nextval, 2, 1, 'V', 'U', null, null, null, null, sysdate, sysdate);
INSERT INTO ITEM_MEDIUM (ITEM_MEDIUM_ID, ITEM_ID, MEDIUM_ID, ARCHIVE_STATUS, TYPE, STATUS, QUANTITY, START_CONSUMPTION_DATE, END_CONSUMPTION_DATE, CREATE_DATE, LAST_MODIFIED)
            VALUES (ITEM_MEDIUM_SEQ.nextval, 3, 3, 'V', 'R', null, 6, null, null, sysdate, sysdate);

SELECT IM.ITEM_MEDIUM_ID, I.NAME, I.DESCRIPTION, I.BRAND, IM.QUANTITY
FROM ITEM_MEDIUM IM JOIN ITEM I ON IM.ITEM_ID = I.ITEM_ID
WHERE IM.TYPE = 'U'
ORDER BY IM.LAST_MODIFIED DESC
FETCH FIRST 5 ROWS ONLY;

SELECT IM.ITEM_MEDIUM_ID, I.NAME, I.DESCRIPTION, I.BRAND, IM.QUANTITY
FROM ITEM_MEDIUM IM JOIN ITEM I ON IM.ITEM_ID = I.ITEM_ID
WHERE IM.TYPE = 'R' OR IM.TYPE = 'C'
ORDER BY IM.LAST_MODIFIED DESC
FETCH FIRST 5 ROWS ONLY;

SELECT *
FROM LOCATION
ORDER BY LAST_MODIFIED DESC
FETCH FIRST 5 ROWS ONLY;

SELECT *
FROM MEDIUM
ORDER BY LAST_MODIFIED DESC
FETCH FIRST 5 ROWS ONLY;

SELECT ITEM_MEDIUM_ID, I.NAME, I.CODENAME, I.BRAND, M.NAME AS MEDIUM_NAME, L.NAME AS LOCATION_NAME, IM.CREATE_DATE, IM.LAST_MODIFIED
FROM ITEM_MEDIUM IM JOIN ITEM I ON IM.ITEM_ID = I.ITEM_ID
                    JOIN MEDIUM M on IM.MEDIUM_ID = M.MEDIUM_ID
                    JOIN LOCATION L ON M.PARENT_LOCATION = L.LOCATION_ID
WHERE IM.TYPE = 'U' AND IM.ARCHIVE_STATUS = 'V'
ORDER BY ITEM_MEDIUM_ID;

SELECT ITEM_MEDIUM_ID, I.NAME, I.CODENAME, I.BRAND, IM.QUANTITY, M.NAME AS MEDIUM_NAME, L.NAME AS LOCATION_NAME, IM.CREATE_DATE, IM.LAST_MODIFIED, IM.START_CONSUMPTION_DATE, IM.END_CONSUMPTION_DATE
FROM ITEM_MEDIUM IM JOIN ITEM I ON IM.ITEM_ID = I.ITEM_ID
                    JOIN MEDIUM M on IM.MEDIUM_ID = M.MEDIUM_ID
                    JOIN LOCATION L ON M.PARENT_LOCATION = L.LOCATION_ID
WHERE (IM.TYPE = 'R' OR IM.TYPE = 'C') AND IM.ARCHIVE_STATUS = 'V'
ORDER BY ITEM_MEDIUM_ID;

SELECT ITEM_MEDIUM_ID, I.NAME, I.CODENAME, I.BRAND, IM.QUANTITY, M.NAME AS MEDIUM_NAME, L.NAME AS LOCATION_NAME, IM.CREATE_DATE, IM.LAST_MODIFIED, IM.START_CONSUMPTION_DATE, IM.END_CONSUMPTION_DATE
FROM ITEM_MEDIUM IM JOIN ITEM I ON IM.ITEM_ID = I.ITEM_ID
                    JOIN MEDIUM M on IM.MEDIUM_ID = M.MEDIUM_ID
                    JOIN LOCATION L ON M.PARENT_LOCATION = L.LOCATION_ID
WHERE IM.ARCHIVE_STATUS = 'A'
ORDER BY ITEM_MEDIUM_ID;

SELECT *
FROM LOCATION
WHERE PARENT_LOCATION IS NULL;

SELECT IM.*, I.NAME AS NAME, I.BRAND AS BRAND
FROM ITEM_MEDIUM IM JOIN ITEM I ON IM.ITEM_ID = I.ITEM_ID
WHERE IM.MEDIUM_ID IN (
    SELECT M.MEDIUM_ID
    FROM MEDIUM M
    START WITH M.MEDIUM_ID = ?
    CONNECT BY PRIOR M.MEDIUM_ID = M.PARENT_MEDIUM
);

SELECT IM.*, I.NAME AS NAME, M.NAME AS MEDIUM_NAME, L.NAME AS LOCATION_NAME
FROM ITEM_MEDIUM IM JOIN ITEM I ON IM.ITEM_ID = I.ITEM_ID
                    JOIN MEDIUM M ON IM.MEDIUM_ID = M.MEDIUM_ID
                    JOIN LOCATION L ON M.PARENT_LOCATION = L.LOCATION_ID
WHERE IM.ITEM_ID = ?;

SELECT *
FROM MEDIUM
WHERE PARENT_LOCATION = ? AND MEDIUM_ID NOT IN (
    SELECT M.MEDIUM_ID
    FROM MEDIUM M
    START WITH M.MEDIUM_ID = ?
    CONNECT BY PRIOR M.MEDIUM_ID = M.PARENT_MEDIUM
);

SELECT COUNT(*) - 1
FROM LOCATION L
START WITH L.LOCATION_ID = ?
CONNECT BY PRIOR L.LOCATION_ID = L.PARENT_LOCATION

SELECT *
FROM LOCATION
WHERE PARENT_LOCATION IS NULL AND LOCATION_ID != ?;

SELECT *
FROM LOCATION;

COMMIT;